### ISSUE TITLE
Clarification of use of crypto?

### ISSUE THREAD

**Issue by ramriot** [networkprotocol/netcode.io#6]
Hi  There,

Really good idea for a protocol but I'm somewhat concerned by how your apparent useage of AEAD in the protocol.

1/ I can see a static private_key variable apparently included in both the server & client source, if it really is a private key then sharing it like this means its no longer private.

2/ When the private_key variable is used in crypto_aead_chacha20poly1305_encrypt function as parameter key it is I believe is expecting a symmetric key and not an asymmetric private key.

**Comment by gafferongames** [comment]
Thanks. 

In a real application, the private key is a symmetric key known only to to the web backend (which generates the connect token), and the dedicated server instances.

At no point does the client know the private key.

Unfortunately, due to a lack of time, the example client.c also knows the private key. This is not meant as an example of usage. Normally, the client would request a connect token over REST call, and not know the private key, and pass that connect token into the connect call (and be unable to generate, modify or inspect it).

cheers
