### ISSUE TITLE
Why use 64 bit fields in protocol

### ISSUE THREAD

**Issue by ClosetMonkey** [networkprotocol/netcode.io#74]
I noticed in a few areas that you are using 64 bit fields in area's that don't seem necessary. For example, 32 bits would allow ~~2,147,483,647~~ 4,294,967,295 user id's which seems like it should be well over enough. Same for protocol id. Timestamps don't need to be 64 bit unless timeouts need to be to the millisecond since Jan 01 1970. I'm pretty sure you can get it down to the millisecond within the same month using 32 bits or less. Not to criticize, just wondering if any specific reasons exist.

**Comment by gafferongames** [comment]
User Id is often used to represent the 64bit steam ID or 64bit Xuid for xbox-live, or the 64bit PSN ID... so that’s why it’s 64bits.

Protocol ID is 64bits to let users of netcode.io use a high quality hash function, eg. Hash their data, network protocol version whatever, with a very low probability of collision.

As to why timeouts are milliseconds? That does seem a bit excessive, but it’s too late to change now.

Cheers :)

- Glenn
